#!/usr/bin/env python3
"""Generate an Ansible inventory for a deployed tonic-h3 benchmark scenario.

Queries Azure (via the `az` CLI) for the client/server VMs in a resource group,
reads their PRIVATE and management PUBLIC IPs, and writes an INI inventory with a
`bench` group of two hosts (`client`, `server`). Each host records:

  * ansible_host  - the address Ansible connects to (public IP by default, or the
                    private IP with --connect-via private when the control node is
                    inside the VNet, e.g. a jumpbox / Bastion tunnel).
  * private_ip    - the VM's private IP (the peer-connectivity target).
  * peer          - the name of the other host, so a playbook can look up
                    `hostvars[peer].private_ip` and ping across the private link.
  * vm_name       - the underlying Azure VM name (e.g. `tonich3-server-l3nbfj`),
                    so a playbook can record the real VM identity in run metadata.

No third-party Python packages are required (stdlib + the `az` CLI only).

Examples:
  ./inventory.py --topology cross-region
  ./inventory.py --resource-group rg-tonich3-bench-same-zone --ssh-key ~/.ssh/id_ed25519
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

DEFAULT_USER = "azureuser"
DEFAULT_SSH_KEY = "~/.ssh/id_ed25519"
TOPOLOGIES = ("same-zone", "cross-zone", "cross-region")


def eprint(*args: object) -> None:
    print(*args, file=sys.stderr)


def az_json(args: list[str]) -> object:
    """Run an `az` command and parse its JSON stdout."""
    cmd = ["az", *args, "--output", "json"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except FileNotFoundError:
        eprint("ERROR: the Azure CLI (`az`) was not found on PATH.")
        sys.exit(2)
    except subprocess.CalledProcessError as exc:
        eprint(f"ERROR: `{' '.join(cmd)}` failed:\n{exc.stderr.strip()}")
        sys.exit(exc.returncode or 1)
    return json.loads(proc.stdout or "null")


def classify(name: str) -> str | None:
    """Map a VM name to the logical role by its role token.

    Names follow `<prefix>-<role>-<suffix>` (e.g. `tonich3-client-l3nbfj`), so the
    role sits between dashes; also tolerate a trailing `-role` with no suffix.
    """
    lowered = name.lower()
    if "-client-" in lowered or lowered.endswith("-client"):
        return "client"
    if "-server-" in lowered or lowered.endswith("-server"):
        return "server"
    return None


def collect_nodes(resource_group: str) -> dict[str, dict[str, str]]:
    """Return {role: {name, private_ip, public_ip}} for the client and server VMs."""
    raw = az_json(["vm", "list-ip-addresses", "--resource-group", resource_group])
    if not raw:
        eprint(f"ERROR: no VMs found in resource group '{resource_group}'.")
        eprint("       Has the deployment finished? Check `az vm list -g <rg> -o table`.")
        sys.exit(1)

    nodes: dict[str, dict[str, str]] = {}
    for entry in raw:
        vm = entry.get("virtualMachine", {})
        name = vm.get("name", "")
        role = classify(name)
        if role is None:
            continue
        network = vm.get("network", {})
        private_ips = network.get("privateIpAddresses") or []
        public_ips = [
            p.get("ipAddress", "")
            for p in (network.get("publicIpAddresses") or [])
            if p.get("ipAddress")
        ]
        if not private_ips:
            eprint(f"ERROR: VM '{name}' has no private IP yet; is the NIC ready?")
            sys.exit(1)
        nodes[role] = {
            "name": name,
            "private_ip": private_ips[0],
            "public_ip": public_ips[0] if public_ips else "",
        }

    missing = [r for r in ("client", "server") if r not in nodes]
    if missing:
        eprint(f"ERROR: could not find these roles in '{resource_group}': {', '.join(missing)}")
        eprint("       Expected VM names containing '-client-'/'-server-' (or ending in '-client'/'-server').")
        sys.exit(1)
    return nodes


def build_inventory(
    nodes: dict[str, dict[str, str]],
    *,
    user: str,
    ssh_key: str,
    connect_via: str,
) -> str:
    peer_of = {"client": "server", "server": "client"}
    lines: list[str] = [
        "# Generated by tests/infra/ansible/inventory.py - do not edit by hand.",
        "# Regenerate after each deployment (private IPs change per deploy).",
        "[bench]",
    ]
    for role in ("client", "server"):
        node = nodes[role]
        connect_ip = node["private_ip"] if connect_via == "private" else node["public_ip"]
        if not connect_ip:
            eprint(
                f"ERROR: {role} VM '{node['name']}' has no public IP "
                "(deployed with --no-public-ip / Bastion mode)."
            )
            eprint(
                "       Re-run with --connect-via private and run this playbook from "
                "inside the VNet (jumpbox / Bastion tunnel)."
            )
            sys.exit(1)
        lines.append(
            f"{role} ansible_host={connect_ip} "
            f"private_ip={node['private_ip']} peer={peer_of[role]} "
            f"vm_name={node['name']}"
        )

    lines += [
        "",
        "[bench:vars]",
        f"ansible_user={user}",
        f"ansible_ssh_private_key_file={ssh_key}",
        "ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write an Ansible inventory for a deployed benchmark scenario.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-g", "--resource-group", help="Resource group holding the VMs.")
    group.add_argument(
        "-t",
        "--topology",
        choices=TOPOLOGIES,
        help="Derive the resource group as rg-tonich3-bench-<topology>.",
    )
    parser.add_argument("-u", "--user", default=DEFAULT_USER, help="SSH admin username.")
    parser.add_argument(
        "-k",
        "--ssh-key",
        default=DEFAULT_SSH_KEY,
        help="Path to the SSH PRIVATE key used to reach the VMs.",
    )
    parser.add_argument(
        "--connect-via",
        choices=("public", "private"),
        default="public",
        help="Address Ansible connects to: public IP, or private IP (from inside the VNet).",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=str(Path(__file__).resolve().parent / "inventory.ini"),
        help="Inventory file to write.",
    )
    args = parser.parse_args()

    resource_group = args.resource_group or f"rg-tonich3-bench-{args.topology}"
    nodes = collect_nodes(resource_group)
    inventory = build_inventory(
        nodes,
        user=args.user,
        ssh_key=os.path.expanduser(args.ssh_key),
        connect_via=args.connect_via,
    )

    output_path = Path(args.output)
    output_path.write_text(inventory, encoding="utf-8")

    print(f"Resource group : {resource_group}")
    for role in ("client", "server"):
        n = nodes[role]
        print(f"  {role:<6} {n['name']:<28} private={n['private_ip']:<15} public={n['public_ip'] or '-'}")
    print(f"Inventory      : {output_path}")
    print("Next           : ansible-playbook -i "
          f"{output_path.name} {Path(__file__).with_name('ping.yml').name}")


if __name__ == "__main__":
    main()
