[package]
name = "tonic-s2n"
version = "0.1.0"
edition = "2021"

[dependencies]
s2n-quic-h3.workspace = true
tonic-h3.workspace = true
http.workspace = true
s2n-quic.workspace = true
hyper.workspace = true
tracing.workspace = true