[package]
name = "tonic-h3"
version = "0.1.0"
edition = "2021"

[dependencies]
futures.workspace = true
h3-quinn.workspace = true
h3.workspace = true
http.workspace = true
hyper-util.workspace = true
hyper.workspace = true
tokio.workspace = true
tonic.workspace = true
tower.workspace = true
tracing.workspace = true
